---
title: "fml"
output: html_document
date: "2023-09-10"
---
#part 1- importing the data
#The source of the data set:https://www.kaggle.com/datasets/sidtwr/videogames-sales-dataset

```{r}
a<-read.csv("C:/Users/LENOVO/Downloads/PS4_GamesSales.csv")
a

```
#part 2**-descriptive statistics for quantitative variables

```{r}
summary(a)
```


```{r}
mean(a$Global)
```
ī
```{r}
median(a$Global)
```
ī
```{r}
sum(a$Global)
```


```{r}
sd(a$Global)
```


```{r}
var(a$Global)
```


```{r}
max(a$Global)
```

```{r}
min(a$Global)
```


```{r}
str(a$Global)
```
#part3 **-descriptive statistics for categorical variables

```{r}
table(a$Genre)
```


```{r}
a$Genre
```


```{r}
table(a$Publisher)
```


```{r}
str(a$Genre)
```
#transforming the variables

```{r}
log(a$Global)
```


```{r}
log(a$Rest.of.World)
```


```{r}
c<-a$Global-mean(a$Global)/sd(a$Global)
c
```

#part 5-plotting the one variables
```{r}
hist(a$Global,main="HISTOGRAM OF GLOBAL")
```
#part6-scatterplot

```{r}
plot(a$Global,a$Rest.of.World,main="scatterplot")

```


```{r}

```